apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-word-search
  labels:
    app: coffee-word-search
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coffee-word-search
  template:
    metadata:
      labels:
        app: coffee-word-search
    spec:
      containers:
      - name: coffee-word-search
        image: acnagy/coffee-word-search:0.3.0-18
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
