version: 2
jobs:
  build:
    working_directory: ~/coffee-word-search
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: test
          command: gradle clean test
      - run: 
          name: build
          command: gradle clean build -x test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build & push container
          command : |
            cd ~/coffee-word-search
            export TAG=0.3.0-${CIRCLE_BUILD_NUM}
            export IMAGE_NAME=coffee-word-search
            docker build -t acnagy/$IMAGE_NAME:$TAG .
            echo $DOCKER_HUB_PWD | docker login -u $DOCKER_HUB_USER --password-stdin
            docker push acnagy/$IMAGE_NAME:$TAG
