version: 2
jobs:
  build:
    working_directory: ~/coffee-word-search
    docker:
      - image: circleci/openjdk:11-stretch-node-browsers-legacy
    steps:
      - checkout
      - run: 
          name: build
          command: gradle build
      - run:
          name: test
          command: gradle clean test
      - run:
          name: build & push docker
          command : |
            echo 'export TAG=0.2.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=coffee-word-search' >> $BASH_ENV
            docker build -t acnagy/$IMAGE_NAME:$TAG
            echo $DOCKER_HUB_PWD | docker login -u $DOCKER_HUB_USER --password-stdin
            docker push acnagy/$IMAGE_NAEM:$TAG
